# Options:
# - target (REQUIRED)
# - Configuration file


---

- hosts: '{{ target }}'
  vars:
     config_path: "'{{ config|default('') }}'"
     config_data: "{{ lookup('file', config) }}"

  tasks:
    - name: Install or update Simple Monitor Alert
      pip: state=latest name='git+https://github.com/Nekmo/simple-monitor-alert.git@{{ branch|default("master")
           }}#egg=simple-monitor-alert' editable=no
      become: yes
      become_method: sudo
    - name: Copy configuration
      blockinfile: block='{{ config_data }}' dest=/etc/simple-monitor-alert/sma.ini
      become: yes
      become_method: sudo
      when: config_path
